name: flutterai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.15.1
  firebase_ui_auth: ^1.10.0
  firebase_core: ^2.24.1
  firebase_storage: ^11.5.4
  cloud_firestore: ^4.7.0
  image_picker: ^1.0.5
  universal_html: ^2.0.4
  file_picker: ^4.0.10
  cached_network_image: ^3.3.0
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
